"""Fix model:  Anime Material

Revision ID: 97e619833882
Revises: c2df2a543f9f
Create Date: 2025-09-25 08:46:04.042610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e619833882'
down_revision: Union[str, None] = 'c2df2a543f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False, comment='Дата последнего обновления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('anime_material_genres',
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['anime_material.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_id', 'genre_id')
    )
    op.add_column('anime_material', sa.Column('anime_kind', sa.String(), nullable=True))
    op.add_column('anime_material', sa.Column('episodes_total', sa.Integer(), nullable=True))
    op.add_column('anime_material', sa.Column('episodes_aired', sa.Integer(), nullable=True))
    op.add_column('anime_material', sa.Column('rating_mpaa', sa.String(), nullable=True))
    op.add_column('anime_material', sa.Column('minimal_age', sa.Integer(), nullable=True))
    op.add_column('anime_material', sa.Column('anime_status', sa.String(), nullable=True))
    op.add_column('anime_material', sa.Column('premiere_world', sa.Date(), nullable=True))
    op.add_column('anime_material', sa.Column('premiere_ru', sa.Date(), nullable=True))
    op.drop_column('anime_material', 'genres')
    op.drop_column('anime_material', 'type')
    op.drop_column('anime_material', 'age_limit')
    op.drop_column('anime_material', 'premiere_date')
    op.drop_column('anime_material', 'status')
    op.drop_column('anime_material', 'released_episodes_count')
    op.drop_column('anime_material', 'mpaa_rating')
    op.drop_column('anime_material', 'episodes_count')
    op.drop_column('anime_material', 'studio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime_material', sa.Column('studio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('anime_material', sa.Column('episodes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('anime_material', sa.Column('mpaa_rating', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('anime_material', sa.Column('released_episodes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('anime_material', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('anime_material', sa.Column('premiere_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('anime_material', sa.Column('age_limit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('anime_material', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('anime_material', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('anime_material', 'premiere_ru')
    op.drop_column('anime_material', 'premiere_world')
    op.drop_column('anime_material', 'anime_status')
    op.drop_column('anime_material', 'minimal_age')
    op.drop_column('anime_material', 'rating_mpaa')
    op.drop_column('anime_material', 'episodes_aired')
    op.drop_column('anime_material', 'episodes_total')
    op.drop_column('anime_material', 'anime_kind')
    op.drop_table('anime_material_genres')
    op.drop_table('genre')
    # ### end Alembic commands ###
