"""Added fields for working with episodes in Anime Material

Revision ID: c2df2a543f9f
Revises: c968b4841319
Create Date: 2025-09-22 05:33:07.516389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2df2a543f9f'
down_revision: Union[str, None] = 'c968b4841319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime_material', sa.Column('released_episodes_count', sa.Integer(), nullable=True))
    op.add_column('anime_material', sa.Column('last_season', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime_material', 'last_season')
    op.drop_column('anime_material', 'released_episodes_count')
    # ### end Alembic commands ###
